### ISSUE TITLE
Matray news via http proxy

### ISSUE THREAD

**Issue by realsimix** [moson-mo/matray#12]
Hi,

Is there a way to make matray work through a http proxy?

I have proxy environment vars set the way they are used by tools like wget or curl, but they don't make matray sending its http requests via proxy.

Thanks,
Simon

**Comment by moson-mo** [comment]
Hi,

Actually it should be using libproxy in the background which should be able to figure it out then.

Which DE are you using?

Could you run: `_PX_DEBUG=1 matray`
That should reveal where it's trying to get the proxy setting from...

regards,
MO

**Comment by realsimix** [comment]
You're right, I can see that libproxy is being loaded by matray.

I'm using KDE on current Manjaro/ARM:

```
$ _PX_DEBUG=1 matray

matray started.
Configuration extension is: 20kde_config_extension
Ignored list is: 
Config is: 
        direct://
Error occured fetching news:
Cannot connect to destination
```

Should matray use a KDE specific proxy configuration somehow?

I have generic proxy environment set like this:

```
http_proxy=http://proxy:8080
https_proxy=http://proxy:8080
HTTP_PROXY=http://proxy:8080
HTTPS_PROXY=http://proxy:8080
```
Thanks,
Simon

**Comment by moson-mo** [comment]
I'm not a KDE user, but I assume there is some possibility to set proxy settings in the "System Settings" in Plasma.
libproxy seems to pick those ones up...

**Comment by realsimix** [comment]
Thanks, found it and it works. Despite the proxy env vars being set, one has to configure KDE to use these vars.
