### ISSUE TITLE
Missing icons when using the "system" icon theme

### ISSUE THREAD

**Issue by Photon89** [moson-mo/matray#13]
When using the "system" icon theme the tray icon is not present (just some space is reserved in the panel but no icon is shown). The icon in the notification bubble is broken (a "missing icon" icon is shown).

**Comment by moson-mo** [comment]
With the "System" option it falls back to "mntray-regular" and "mntray-news" icons (from the previous mntray tool).
Some icon themes were delivering icons for mntray (like Papirus)...
So if the icon theme you're using is not providing those icons you'll see a *broken-image* icon...
