### ISSUE TITLE
Typo in english, and translation related question

### ISSUE THREAD

**Issue by Zorrototo** [moson-mo/matray#14]
There is a typo in the english language files, it is written 'occured' instead of 'occurred'

Also I was willing to send a french translation file, but I couldn't find a way to test it. I tried to build following the README (and I tried to name the file and the Language line to "fr" and "fr_FR", as well as adding the value to the LINGUAS file too), but when I start the executable it is in english instead of french. 

Is there something specific to do?

**Comment by moson-mo** [comment]
For applying changes to translations, those would need to be installed in order to see it in the app.
`ninja -C build install`

You can just copy "de" to "fr", make the changes and make a pull request. I'll have a look at the "occured" thing...

**Comment by Zorrototo** [comment]
I was unable to have it to work. So in the end I can't verify my translation fits the UI, and the different cases by using simply "fr" and/or the various other french variants (which are the same language). I will create a PR for the language file itself, with no verification made to it sorry.

//EDIT: done https://github.com/moson-mo/matray/pull/15

//EDIT2: if it helps here are the variants for French language, there is no difference, at least for such program (no currency/temperature unit so it should be all the same here):

Belgium: fr_BE
Canada:  fr_CA
Switzerland: fr_CH
France: fr_FR
Luxembourg: fr_LU

I made just a "fr" lang file in the hope it will work for all. In the end it may be required to have all variants, I don't know.

**Comment by moson-mo** [comment]
Thanks. Merged it.

If you want to try it out:

```
mkdir matray-git
cd matray-git
wget "https://raw.githubusercontent.com/moson-mo/matray/master/resources/misc/PKGBUILD"
makepkg -i
```

What's your language setting, fr_FR ? 

> I made just a "fr" lang file in the hope it will work for all. In the end it may be required to have all variants, I don't know.

I'd assume it will fall back to "fr", not sure either though :)

**Comment by Zorrototo** [comment]
Installing this way worked for me, the language is directly assigned to the program (it wasn't working when I tried different ways with ninja build install)
Yes my locale is fr_FR
