### ISSUE TITLE
Possibility of opening infinite Settings windows

### ISSUE THREAD

**Issue by Zorrototo** [moson-mo/matray#16]
You can open infinite number of Settings windows by right clicking the icon in tray, and clicking Settings in menu; instead of switching to the already opened Settings window.

**Comment by moson-mo** [comment]
Thanks for noticing. Will have a look.

*edit*
Should be fixed now. Can you confirm?  

Thanks,  
MO

**Comment by Zorrototo** [comment]
Yep it is fixed :+1:
