### ISSUE TITLE
KDE Plasma notification quirks

### ISSUE THREAD

**Issue by acarasimon96** [moson-mo/matray#8]
On the KDE Plasma desktop, matray notifications are being sent as if they come from something called Plasma Workspace (the desktop itself). Clicking the Configure button next to the Close button opens a popup with different notification types for Plasma Workspace, with the generic Notification type being highlighted automatically (see second image). This explains why notifications from matray use the wrong app name on their headers, and any settings for that type apply to matray as well. For example, if you disable sound for generic Plasma notifications, you won't get any sound the next time a new Manjaro news item arrives.

This does not happen with mntray, which used its own app name in the notification header and had its own app entry in the notification settings.

![Screenshot_20210607_161735](https://user-images.githubusercontent.com/17580077/121096100-c0ee1f00-c7ae-11eb-8a92-3e4549335315.png)
![Screenshot_20210607_162942](https://user-images.githubusercontent.com/17580077/121096108-c3e90f80-c7ae-11eb-8341-a87ef3269da4.png)

**Comment by moson-mo** [comment]
Hmm. I tried it a fresh VM with KDE:


![image](https://user-images.githubusercontent.com/13588013/121175727-b178df80-c85b-11eb-8015-311892e3d71d.png)

![image](https://user-images.githubusercontent.com/13588013/121175879-de2cf700-c85b-11eb-8fa9-d6bd66ce1cd0.png)

Any idea what could be different?

**Comment by acarasimon96** [comment]
I guess you got the expected behavior on your end, so this looks more of an issue with my Manjaro setup. In fact, I've also had this happen with Pamac Manager, which is a GTK3 app and despite being listed in the Notifications settings window, so it seems all GTK3 apps are affected by this at least for me. I'm not sure if this is caused by a missing package or config files not updating properly. I'll have to seek help on the Manjaro forum for possible solutions before I proceed with this issue.
